FROM node:18-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json ./
RUN  yarn install

# Rebuild the source code only when needed
FROM node:18-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN yarn run build

EXPOSE 3000

ENV NEXT_PUBLIC_BASE_URL=http://localhost:3001

CMD ["node", "server.js"]