db_username   = "root"
db_password   = "bovippro123"
db_name       = "conduit"
db_identifier = "something"
jwt_secret    = "itsVeryStrong"
be_image_name = "turbo-be"
fe_image_name = "turbo-fe"
ecs_role_name = "arn:aws:iam::932782693588:role/IAMECSTaskRole"